name: Zlaten del Castillo
favicon: null
layout_spectrum: 0.74989
typography_spectrum: 1
title: VFX Supervisor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#122a36'
    - '#f0e6d5'
    - '#709174'
    - '#ca813d'
    - '#24483a'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.868528519757092
  rhythmicContrast: 0.75
purpose: []
